# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SoundEffect',
            fields=[
                ('sid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sound_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('tags', models.CharField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soundeffects.Categories')),
            ],
        ),
    ]
