# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundeffects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundeffect',
            name='sound_file',
            field=models.FileField(default='none', upload_to=b''),
        ),
    ]
