# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundeffects', '0002_soundeffect_sound_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundeffect',
            name='sound_file',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
